#!/usr/bin/env bash
#
# setup_brand_env.sh — one-shot configurator for the Primus public
# brand / compliance pages (api.primustech.in/, /contact-us, etc.).
#
# Writes docker-compose.override.yml with the brand env vars the
# backend reads at boot, then recreates the backend container so the
# values become live.
#
# Run from the directory containing docker-compose.yml:
#     cd ~/Primusbackend/backend
#     sudo bash scripts/setup_brand_env.sh
#
# Override any value before running, e.g.:
#     PRIMUS_BUSINESS_PHONE="+91-9999999999" \
#     PRIMUS_BUSINESS_GSTIN="36ABCDE1234F1Z5" \
#       bash scripts/setup_brand_env.sh
#
# Safe to re-run: every run rewrites the override file with the
# current values and restarts only the backend service. Other
# containers (redis, celery, nginx, cloudflared) are left running.

set -euo pipefail

# ── Defaults (current production values) ───────────────────────────
PRIMUS_BUSINESS_NAME="${PRIMUS_BUSINESS_NAME:-Primus Technologies}"
PRIMUS_BUSINESS_EMAIL="${PRIMUS_BUSINESS_EMAIL:-support@primusadmin.in}"
PRIMUS_BUSINESS_PHONE="${PRIMUS_BUSINESS_PHONE:-+91-9392777989}"
PRIMUS_BUSINESS_ADDRESS="${PRIMUS_BUSINESS_ADDRESS:-4th Floor, Block 3, Hitech City Rd, Patrika Nagar, Madhapur, Hyderabad, Telangana 500081}"
# Default tagline pulled out separately because bash's ${VAR:-default}
# default-clause parses single-quotes; an apostrophe inside it (e.g.
# "India's") opens an unbalanced single-quote string and breaks the
# whole script. Single-quoted literal + concat-escape the apostrophe.
_DEFAULT_TAGLINE='Self-service kiosks, dynamic inventory, and instant payments for India'\''s gaming cafés.'
PRIMUS_BUSINESS_TAGLINE="${PRIMUS_BUSINESS_TAGLINE:-$_DEFAULT_TAGLINE}"
PRIMUS_BUSINESS_HOURS="${PRIMUS_BUSINESS_HOURS:-Monday – Saturday · 10:00 – 19:00 IST}"
PRIMUS_BUSINESS_CITY="${PRIMUS_BUSINESS_CITY:-Hyderabad}"
PRIMUS_BUSINESS_WEBSITE="${PRIMUS_BUSINESS_WEBSITE:-https://primustech.in}"
PRIMUS_BUSINESS_GSTIN="${PRIMUS_BUSINESS_GSTIN:-}"
PRIMUS_GRIEVANCE_NAME="${PRIMUS_GRIEVANCE_NAME:-Grievance Officer}"
PRIMUS_GRIEVANCE_EMAIL="${PRIMUS_GRIEVANCE_EMAIL:-grievance@primustech.in}"

# ── Sanity ─────────────────────────────────────────────────────────
if [[ ! -f docker-compose.yml ]]; then
  echo "error: docker-compose.yml not found in current directory ($PWD)." >&2
  echo "       run this script from the backend folder (~/Primusbackend/backend)." >&2
  exit 1
fi

OVERRIDE=docker-compose.override.yml

if [[ -f "$OVERRIDE" ]]; then
  ts=$(date +%Y%m%d-%H%M%S)
  cp "$OVERRIDE" "${OVERRIDE}.bak.${ts}"
  echo "→ existing override backed up to ${OVERRIDE}.bak.${ts}"
fi

# Escape any double-quote characters in values so the YAML stays valid.
yaml_q() { printf '%s' "$1" | sed 's/"/\\"/g'; }

# ── Write override ─────────────────────────────────────────────────
cat > "$OVERRIDE" <<EOF
# Generated by scripts/setup_brand_env.sh — do not edit by hand.
# Re-run the script (or set env vars and re-run) to update.
# Compose merges this with docker-compose.yml automatically.

services:
  backend:
    environment:
      PRIMUS_BUSINESS_NAME: "$(yaml_q "$PRIMUS_BUSINESS_NAME")"
      PRIMUS_BUSINESS_TAGLINE: "$(yaml_q "$PRIMUS_BUSINESS_TAGLINE")"
      PRIMUS_BUSINESS_EMAIL: "$(yaml_q "$PRIMUS_BUSINESS_EMAIL")"
      PRIMUS_BUSINESS_PHONE: "$(yaml_q "$PRIMUS_BUSINESS_PHONE")"
      PRIMUS_BUSINESS_ADDRESS: "$(yaml_q "$PRIMUS_BUSINESS_ADDRESS")"
      PRIMUS_BUSINESS_HOURS: "$(yaml_q "$PRIMUS_BUSINESS_HOURS")"
      PRIMUS_BUSINESS_CITY: "$(yaml_q "$PRIMUS_BUSINESS_CITY")"
      PRIMUS_BUSINESS_WEBSITE: "$(yaml_q "$PRIMUS_BUSINESS_WEBSITE")"
      PRIMUS_BUSINESS_GSTIN: "$(yaml_q "$PRIMUS_BUSINESS_GSTIN")"
      PRIMUS_GRIEVANCE_NAME: "$(yaml_q "$PRIMUS_GRIEVANCE_NAME")"
      PRIMUS_GRIEVANCE_EMAIL: "$(yaml_q "$PRIMUS_GRIEVANCE_EMAIL")"
EOF

echo "→ wrote $OVERRIDE"

# ── Restart backend so the new vars take effect ────────────────────
echo "→ recreating backend container…"
if command -v docker &>/dev/null && docker compose version &>/dev/null; then
  docker compose up -d --force-recreate backend
elif command -v docker-compose &>/dev/null; then
  docker-compose up -d --force-recreate backend
else
  echo "error: neither 'docker compose' nor 'docker-compose' is available." >&2
  exit 1
fi

# ── Verify ─────────────────────────────────────────────────────────
echo
echo "→ env vars now active inside the container:"
docker compose exec -T backend env 2>/dev/null \
  | grep '^PRIMUS_' \
  | sort \
  || echo "  (could not list — check 'docker compose logs backend')"

echo
echo "✓ Done. Pages live at:"
echo "  https://api.primustech.in/"
echo "  https://api.primustech.in/contact-us"
echo "  https://api.primustech.in/products"
echo "  https://api.primustech.in/terms"
echo "  https://api.primustech.in/refunds"
echo "  https://api.primustech.in/privacy-policy"
echo
echo "Refresh /contact-us in a browser to confirm the phone, email, and address render correctly."
