version: "3.9"

services:
  falco:
    image: falcosecurity/falco-no-driver:latest
    container_name: primus-falco
    privileged: true
    command: falco -K /etc/falco/falco.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
      - ./falco/rules:/etc/falco/falco.d
    restart: unless-stopped

  loki:
    image: grafana/loki:3.1.1
    container_name: primus-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.1.1
    container_name: primus-promtail
    volumes:
      - /var/log:/var/log
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: primus-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.2.0
    container_name: primus-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    restart: unless-stopped

networks:
  default:
    name: primus-runtime-net


